# GOTAL Configs
GOTAL_CONFIG_DIR=/etc/gotal
# MYSQL
export GOTAL_MYSQL_PASSWORD="MyN3wP4ssw0rd"
export GOTAL_MYSQL_HOST="ec2-52-55-89-220.compute-1.amazonaws.com:3306"
export GOTAL_MYSQL_USERNAME="root"
export GOTAL_MYSQL_DATABASE="temu"
# REDIS
export GOTAL_REDIS_HOST="127.0.0.1"
export GOTAL_REDIS_PORT=6379
export GOTAL_PASSWORD=MyN3wP4ssw0rd
# GRPC SERVER
export GOTAL_APISERVER_GRPC_BIND_ADDRESS="0.0.0.0"
export GOTAL_APISERVER_GRPC_BIND_PORT=8082
# HTTP SERVER
export GOTAL_APISERVER_INSECURE_BIND_ADDRESS="0.0.0.0"
export GOTAL_APISERVER_INSECURE_BIND_PORT=8884
# HTTPS SERVER
export GOTAL_APISERVER_SECURE_BIND_ADDRESS="0.0.0.0"
export GOTAL_APISERVER_SECURE_BIND_PORT=8445
# CERT
export GOTAL_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${GOTAL_CONFIG_DIR}/cert/apiserver.pem
export GOTAL_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${GOTAL_CONFIG_DIR}/cert/apiserver-key.pem
# LOG_DIR
export GOTAL_LOG_DIR=/var/log/gotal
